SS-7557 Finalize the first App Builder template
shapediver/AppBuilderSdk pull request #71
Opened 2024-04-15 08:59 UTC by snabela

2024-04-15 09:01 UTC, snabela commented on src/hooks/ui/useCustomTheme.ts
> +			}),
@mathieu-shapediver here one can now define theme overrides per container

2024-04-16 09:43 UTC, snabela commented on src/hooks/ui/useCustomTheme.ts
> +					}
@mathieu-shapediver in the bottom container, we use scrollbars for the text widgets

2024-04-16 09:45 UTC, snabela commented on src/pages/templates/AppBuilderContainerWrapper.tsx
Wrapper for all AppBuilder containers, providing context to the nodes below it.

2024-04-16 09:54 UTC, snabela commented
@mathieu-shapediver please test here: https://appbuilder.shapediver.com/v1/main/0.3.0-beta.4/?g=iframe9.json
Note that [iframe9.json](https://appbuilder.shapediver.com/v1/main/0.3.0-beta.4/iframe9.json) overrides the AppBuilder output of the model, because there is a bug in the image widget component in GH which I still need to fix.

2024-04-16 13:06 UTC, mathieu-shapediver requested changes
@snabela It seems really f**** stunning!
I would suggest the following things:
* The navbar on the left should be wider. I would go for navbarWidth: { md: 250, lg: 300 } .
* I would set all anchors within text widgets with "target=_blank", which will be crucial for the header bar in particular but in general preferable for all anchors within apps.
* I would add the possibility to override some styling properties of anchors in the template, in particular the text color and the underline property. Specifically for the top header bar: I think the underline property should be set to "never" and by default the color to black.

2024-04-16 13:15 UTC, mathieu-shapediver commented
@snabela Additional thing: I noticed that the left navigation bar has a vertical separation line on the right, but the right container does not have one on the left. We should also have this line for the right container.

2024-04-16 15:10 UTC, snabela commented
> * The navbar on the left should be wider. I would go for navbarWidth: { md: 250, lg: 300 } .

done here: https://github.com/shapediver/ShapeDiverReactExample/pull/71/commits/47743f282a415265e91246104cfc74fe72f63029

> * I would set all anchors within text widgets with "target=_blank", which will be crucial for the header bar in particular but in general preferable for all anchors within apps.
> * I would add the possibility to override some styling properties of anchors in the template, in particular the text color and the underline property. Specifically for the top header bar: I think by default the color should be set to var(--text-color).

done here: https://github.com/shapediver/ShapeDiverReactExample/pull/71/commits/ceaeb6e09e6705c73bf412d9b847ffd5d734aeaf

The color of the anchor is now inherited from the parent by default (this behavior can be controlled by the theme, see the commit). This means you can now color anchors like this in markdown: `:span[[LinkedIn](https://www.linkedin.com/company/intersticestudio/)]{color="red"}`

2024-04-16 15:18 UTC, snabela commented
> @snabela Additional thing: I noticed that the left navigation bar has a vertical separation line on the right, but the right container does not have one on the left. We should also have this line for the right container.

done here: https://github.com/shapediver/ShapeDiverReactExample/pull/71/commits/0adce67aafb44be7374761652be95d4122896ab4

2024-04-16 15:29 UTC, mathieu-shapediver approved these changes

2024-04-16 15:33 UTC, merged